### [Numpy](https://numpy.org/)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Numpy Basic Data Types

In [3]:
my_numbers = [1,2,3,4]
simple_array = np.array(my_numbers)
simple_array

array([1, 2, 3, 4])

In [4]:
type(simple_array)

numpy.ndarray

In [7]:
print("Array shape:", simple_array.shape)
print("Array size:", simple_array.size)
print("Array dimensions:", simple_array.ndim)

Array shape: (4,)
Array size: 4
Array dimensions: 1


In [8]:
my_other_numbers = [[1,2,3,4],[4,5,6,7],[8,9,0,1]]
other_simple_array = np.array(my_other_numbers)
other_simple_array

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 0, 1]])

In [9]:
print("Array shape:", other_simple_array.shape)
print("Array size:", other_simple_array.size)
print("Array dimensions:", other_simple_array.ndim)

Array shape: (3, 4)
Array size: 12
Array dimensions: 2


### Operations between arrays (scalar and vectorial):

In [10]:
A = np.array([[1,2,3],[4,5,6],[8,9,0]])
B = np.array([[2,1,5],[9,2,1],[8,7,6]])

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [12]:
B

array([[2, 1, 5],
       [9, 2, 1],
       [8, 7, 6]])

In [13]:
A + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11,  2]])

In [14]:
A * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [24, 27,  0]])

In [14]:
A / 4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [2.  , 2.25, 0.  ]])

In [15]:
A + B

array([[ 3,  3,  8],
       [13,  7,  7],
       [16, 16,  6]])

In [16]:
A * B

array([[ 2,  2, 15],
       [36, 10,  6],
       [64, 63,  0]])

In [17]:
A.dot(B)

array([[ 44,  26,  25],
       [101,  56,  61],
       [ 97,  26,  49]])

In [18]:
A.T
#A.transpose()

array([[1, 4, 8],
       [2, 5, 9],
       [3, 6, 0]])

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

### Creating arrays:

In [75]:
# https://numpy.org/doc/stable/reference/generated/numpy.arange.html

a = np.arange(20)  # ==> np.arange(0,20,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
a = np.arange(1, 5, 0.2)
a

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [77]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [79]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Modifying Dimensions:

In [20]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

d = c.reshape(2,5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
print(c.shape)
print(d.shape)
print(np.ndim(d))
print(d.dtype.name)

(10,)
(2, 5)
2
int64


### Slicing multidimensional arrays:

In [37]:
d[:, 0:1]

array([[0],
       [5]])

In [36]:
d[0:1, :]

array([[0, 1, 2, 3, 4]])

In [40]:
d[d%2==0]

array([0, 2, 4, 6, 8])

In [41]:
d[~d%2==0]  # negation of condition

array([1, 3, 5, 7, 9])

### Stacking Arrays:

In [83]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
# https://numpy.org/doc/stable/reference/generated/numpy.vstack.html

np.vstack([a, np.arange(4).reshape(1, 4)])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [85]:
# https://numpy.org/doc/stable/reference/generated/numpy.hstack.html

np.hstack([a,np.arange(4).reshape(4, 1)])

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2],
       [12, 13, 14, 15,  3]])

### Datatypes:

In [50]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int64


In [51]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)

float64


In [52]:
x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)

float64


### Useful functions:

In [59]:
grades1 = np.array([1.0, 3, 5.0, 7, 9, 2, 4, 6])

In [86]:
# https://numpy.org/doc/stable/reference/generated/numpy.where.html

np.where(grades1 > 4)

(array([2, 3, 4, 7]),)

In [61]:
np.where(grades1 > 4, 'bigger', 'lower')

array(['lower', 'lower', 'bigger', 'bigger', 'bigger', 'lower', 'lower',
       'bigger'], dtype='<U6')

In [87]:
# https://numpy.org/doc/stable/reference/generated/numpy.argmin.html

grades1.argmin()

0

In [88]:
# https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

grades1.argmax()

4

In [89]:
# https://numpy.org/doc/stable/reference/generated/numpy.argsort.html

grades1.argsort()

array([0, 5, 1, 6, 2, 7, 3, 4])

In [70]:
grades2 = np.array([0.9, 3, 4.9, 7, 9, 4, 4, 6])

In [72]:
# https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html

np.intersect1d(grades1,grades2)

array([3., 4., 7., 9.])

In [73]:
# https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

np.allclose(grades1,grades2, 0.1)

False

In [74]:
np.allclose(grades1,grades2, 0.5)

False